version: 2.1

jobs:
  ui-tests:
    docker:
      - image: circleci/node:14-browsers
    steps:
      - checkout
      - run:
          name: "Install NightwatchJS"
          command: "sudo chown -R 65534:3434 "/root/.npm" && sudo npm install -g nightwatch"
      - run:
          name: "Run ContactUs tests"
          command: "npx nightwatch test/contactUs.js"
      - store_artifacts:
          path: "test-output/night-watch-html-report"

workflows:
  version: 2
  ui-tests-workflow:
    jobs:
      - ui-tests
