# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  ui-tests:
    # Specify the execution environment using the Selenium WebDriver image.
    docker:
      - image: selenium/standalone-chrome
    # Add steps to the job.
    steps:
      - checkout
      - run:
          name: "Install Node.js and NightwatchJS"
          command: |
            curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
            sudo apt-get install -y nodejs
            sudo npm install -g nightwatch
            sudo npm install -g chromedriver@latest
      - run:
          name: "Start ChromeDriver"
          command: "chromedriver --port=9515 &"
      - run:
          name: "Run ContactUs tests"
          command: "npx nightwatch test/contactUs.js"
      - store_artifacts:
          path: "test-output/night-watch-html-report"

# Orchestrate jobs using workflows.
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  version: 2
  ui-tests-workflow:
    jobs:
      - ui-tests
