version: 2.1

jobs:
  ui-tests:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - run:
          name: "Start ChromeDriver"
          background: true
          command: "npx webdriver-manager start"
      - run:
          name: "Install NightwatchJS"
          command: "sudo npm install -g nightwatch"
      - run:
          name: "Run ContactUs tests"
          command: "npx nightwatch test/contactUs.js"
      - store_artifacts:
          path: "test-output/night-watch-html-report"

workflows:
  version: 2
  ui-tests-workflow:
    jobs:
      - ui-tests
