version: 2.1

jobs:
  ui-tests:
    docker:
      - image: circleci/node:14-browsers
    steps:
      - checkout
      - run:
          name: "Install Webdriver Manager and NightwatchJS"
          command: |
            sudo npm install -g webdriver-manager
            sudo npm install -g nightwatch

      - run:
          name: "Update Webdriver Manager"
          command: "webdriver-manager update"

      - run:
          name: "Start ChromeDriver"
          command: "webdriver-manager start &"

      - run:
          name: "Run ContactUs tests"
          command: "npx nightwatch test/contactUs.js"
          background: true

      - save_cache:
          key: ui-tests-cache-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ./node_modules

      - store_artifacts:
          path: "test-output/night-watch-html-report"

workflows:
  version: 2
  ui-tests-workflow:
    jobs:
      - ui-tests
