version: 2.1
jobs:
  ui-tests:
    docker:
      - image: cimg/node:lts-browsers

    steps:
      - checkout
      - run:
          name: "Install Chrome and ChromeDriver"
          command: |
            apt-get update
            apt-get install -yq google-chrome-stable
            wget -N https://chromedriver.storage.googleapis.com/92.0.4515.107/chromedriver_linux64.zip
            unzip chromedriver_linux64.zip
            mv chromedriver /usr/local/bin/chromedriver
            chmod +x /usr/local/bin/chromedriver

      - run:
          name: "Install NightwatchJS"
          command: "npm install -g nightwatch"

      - run:
          name: "Run ContactUs tests"
          command: "npx nightwatch test/contactUs.js"

      - store_artifacts:
          path: "test-output/night-watch-html-report"

workflows:
  version: 2
  ui-tests-workflow:
    jobs:
      - ui-tests
