version: 2.1

jobs:
  ui-tests:
    docker:
      - image: cimg/node:lts-browsers

    steps:
      - checkout
      - run:
          name: "Install NightwatchJS"
          command: "sudo npm install -g nightwatch"

      - run:
          name: "Start ChromeDriver"
          background: true
          command: "sudo npx chromedriver --port=9515"

      - run:
          name: "Run ContactUs tests"
          command: "sudo npx nightwatch test/contactUs.js"

      - store_artifacts:
          path: "test-output/night-watch-html-report"

workflows:
  version: 2
  ui-tests-workflow:
    jobs:
      - ui-tests
