version: 2.1

jobs:
  ui-tests:
    docker:
      - image: circleci/node:14-browsers

    steps:
      - checkout
      - run:
          name: Install NightwatchJS and ChromeDriver
          command: |
            npm install -g nightwatch chromedriver@latest

      - run:
          name: Start ChromeDriver
          background: true
          command: chromedriver --port=9515

      - run:
          name: Run ContactUs tests
          command: npx nightwatch test/contactUs.js

      - store_artifacts:
          path: test-output/nightwatch-html-report

workflows:
  version: 2
  ui-tests-workflow:
    jobs:
      - ui-tests
