version: 2.1
node: circleci/node@4.7

browser-tools: circleci/browser-tools@1.1.0 

jobs:
  ui-tests:
    docker:
      - image: cimg/node:lts-browsers
      
    steps:
      - checkout
      - run:
          name: "Install Webdriver Manager and NightwatchJS"
          command: sudo npm cache clean --force && sudo npm install -g nightwatch

      - run:
          name: "Update Webdriver Manager"
          command: "webdriver-manager update"

      - run:
          name: "Start ChromeDriver"
          command: "webdriver-manager start &"

      - run:
          name: "Run ContactUs tests"
          command: "npx nightwatch test/contactUs.js"
          background: true

      - save_cache:
          key: ui-tests-cache-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ./node_modules

      - store_artifacts:
          path: "test-output/night-watch-html-report"

workflows:
  version: 2
  ui-tests-workflow:
    jobs:
      - ui-tests


      # This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml' version: 2.1 # Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects. #
       See: https://circleci.com/docs/2.0/orb-intro/ orbs: node: circleci/node@4.7 browser-tools: circleci/browser-tools@1.1.0 jobs: test: docker: - image: cimg/node:lts-browsers steps: - checkout - browser-tools/install-browser-tools - node/install-packages - run: command: npm run test - store_test_results: path: /tests_output workflows: e2e-test: jobs: - test

