version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.1
  node: circleci/node@4.7


jobs:
  ui-tests:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - node/install-packages
      - run:
          name: "Run ContactUs tests"
          command: "npx nightwatch test/contactUs.js"

      - store_test_results:
          path: tests_output/
      - store_artifacts:
          path: tests_output/

workflows:
  version: 2
  ui-tests-workflow:
    jobs:
      - ui-tests
